name: nhom4_bmtt_totp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.4
  http: ^1.2.2
  convert: ^3.1.2
  shadcn_flutter: ^0.0.24
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
  